# Generated by Django 3.2.8 on 2021-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='FullName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
