# Generated by Django 3.2.7 on 2021-12-01 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stInfoApp', '0004_faculty_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DoB',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='default', max_length=15),
            preserve_default=False,
        ),
    ]
