# Generated by Django 3.2.7 on 2021-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stInfoApp', '0005_auto_20211201_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ProfileImage',
            field=models.FileField(default='default.png', upload_to='faculties/profile/'),
        ),
        migrations.AddField(
            model_name='student',
            name='ProfileImage',
            field=models.FileField(default='default.png', upload_to='students/profile/'),
        ),
    ]
